# Documentation for schema files like this one is located here:
# https://drupal.org/node/1905070

video_transcode.video_transcode_preset.*:
  type: mapping
  label: 'Preset'
  mapping:
    id:
      type: string
      label: 'Preset id'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Label'
    video_extension:
      type: string
      label: 'Video extension'
    wxh:
      type: string
      label: 'Video size'
    frame_rate:
      type: string
      label: 'Video frame rate'
    video_bitrate:
      type: string
      label: 'Video bitrate'
    audio_bitrate:
      type: string
      label: 'Audio bitrate'
    video_codec:
      type: string
      label: 'Video codec'
    audio_codec:
      type: string
      label: 'Audio codec'
    h264_profile:
      type: string
      label: 'Video h264 profile'
    reference_frames:
      type: string
      label: 'Video reference frames'
    codec_level:
      type: string
      label: 'Video codec level'